version: '3.7'

services:
  db:
    container_name: db
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - cookbook

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
    expose:
      - 8000
    ports: 
      - 9000:8000
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - cookbook
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app/:ro
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - cookbook
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static
    networks:
      - cookbook
networks:
  cookbook:
    driver: bridge