version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - 8000
    ports:
      - '8000:8000'
    restart: always
    command: 'manage.py runserver 0.0.0.0:8000'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - './local_db/postgres/data:/var/lib/postgresql/data'
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
