version: '3.7'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports: 
      - '9000:8000'
    command: "poetry run python manage.py runserver"