version: '3.7'

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
    expose:
      - 8000
    ports: 
      - 9000:8000
    command: python manage.py runserver 0.0.0.0:8000